### PR TITLE
Add characterSet prop

### LINKED ISSUE #78: Lacking support for UTF-8?
It can't display Chinese, Japanese etc

### LINKED ISSUE #127: vs code can't show chinese
how can i fix this , where can set charset on vscode ?  thansk
image

### PR DESCRIPTION
**Pull request by satotake**
fixes #78
(partially fixes #127)

Although these are Japanese letters, they are basically same as Chinese in terms of charset.

Screen Shot 2020-06-16 at 0 02 37

### CODE REVIEW

**Comment by danmarshall** [comment]
Great, thanks so much! 🥇 
Now I'm wondering if we should do this earlier in the process, so that we don't do it every time we create a layer. Can you add it to the [PresenterConfig interface](https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/interfaces.ts#L139)?

**Comment by satotake** [comment]
Thanks for your comment.

I am not sure of who/what uses PresenterConfig interface but ,anyway, I tried.

Is it better to execute it much earlier (for example, before updating stage)? 
If so, users might set `charcterSet`  via [ViewerOptions](https://github.com/microsoft/SandDance/blob/master/packages/sanddance/src/types.ts#L61:18)

**Comment by danmarshall** [comment]
Yes, `viewerOptions` would be the way users set it.

**Comment by satotake** [comment]
Finally, I just added `characterSet` prop to `ViewOptions` and `PresenterConfig`.

**Comment by danmarshall** [comment]
Thanks!!

**Pull request merged**
