### PR TITLE
Vue.js component

### LINKED ISSUE #211: Feature request: Vue.js component

### PR DESCRIPTION
**Pull request by mat-sz**
I've ported the React.js component to Vue, while using Vue's event system instead of callbacks.

E.g.

```
<SandDanceVue
      @mounted="function"
      @error="function"
      @view="function"
/>
```

Resolves #211.

### CODE REVIEW

**Comment by danmarshall** [comment]
Awesome! Thanks 😀. There's a build break, I can take a look at that. Otherwise, is this ready?

**Comment by mat-sz** [comment]
@danmarshall Thank you for handling the build issues, I didn't notice them (good old "works on my machine" :)). I believe that should be ready but please make sure to give it a try on your end.

**Comment by danmarshall** [comment]
I've hit the same build issue on my local machine, I think it may be because of 2 versions of rollup. I will try and consolidate them...

**Comment by danmarshall** [comment]
@mat-sz - do you need the `prepare` script? I think it is running before other commands, such that the sanddance build is not available.

**Comment by mat-sz** [comment]
@danmarshall It's only required if the package will be published directly (which doesn't seem to be the case here).

**Pull request merged**
